chore: revert changed in buildTx types to fix compatibility with ts@4.5
../../../types-legacy/ts4.5/tx/builder/schema.d.ts:4674:72
error TS2536: Type 'V' cannot be used to index type 'TxTypeSchemasNotCombined[T]'.
Found 1 error.
partially reverts 7d473de86bf5eaae6d907c22857d960a1052235f